### ISSUE TITLE
Suggested to update to older version 1.0.0

### ISSUE THREAD

**Issue by yalov** [Sujimichi/KXAPI#1]
KSP 1.6.0, KXAPI 1.1.0 from the CKAN.
Suggested to update to 1.0.0

![default](https://user-images.githubusercontent.com/12796450/50352095-3620f780-0555-11e9-9f0f-b75bb86e1472.jpg)

**Comment by Sujimichi** [comment]
Thanks for letting me know. That's been corrected, you shouldn't see an update available message (for any version) now in KSP 1.6.x.
The incorrect version was being shown as KerbalX hadn't yet had 1.6.x added to the list of recognised KSP versions, so it was defaulting to the initial versions of the mods.
